### ISSUE TITLE
switchtec-user: version.h: No such file or directory

### ISSUE THREAD

**Issue by zone-hai** [thepacketgeek/switchtec-user-sys#1]
I am sorry to ask this question here,but when i try install switchtec-user in  Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-124-generic x86_64),it show the error as follow:
cli/commands.c:27:10: fatal error: version.h: No such file or directory
27 | #include "version.h"
| ^~~~~~~~~~~
how can I fix it?

**Comment by thepacketgeek** [comment]
How and from what directory are you trying to install the library from?

**Comment by zone-hai** [comment]
Thanks a lot, after I executed the file VERSION-GEN, version.h was generated and switchtec-user was installed successfully.
However, I now try to execute "cargo build" in the switchtec-user-sys directory, and the following error occurs:
error: failed to run custom build command for `switchtec-user-sys v0.1.10 (/home/xl/rust/switchtec-user-sys)`

Caused by:
  process didn't exit successfully: `/home/xl/rust/switchtec-user-sys/target/debug/build/switchtec-user-sys-aa0b6384f7fa021a/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unable to generate bindings: NotExist("switchtec-user/inc/switchtec/switchtec.h")', build.rs:28:10
rust version: nightly-x86_64-unknown-linux-gnu

**Comment by zone-hai** [comment]
sorry,the directory of switchtec-user-sys is: /home/xl/rust/switchtec-user-sys;
and the  directory of switchtec-user is: /home/xl/rust/switchtec-user

**Comment by thepacketgeek** [comment]
You shouldn't need to download or install the `switchtec-user` library before building `switchtec-user-sys`.

For the missing `switchtec.h` file, is `/home/xl/rust/switchtec-user-sys/switchtec-user` populated?  One guess is that you downloaded a zip of `switchtec-user-sys` instead of git cloning and the git submodule for `switchtec-user` is not being downloaded (which happens in the `build.rs` script).

Let me know if there are contents inside `/home/xl/rust/switchtec-user-sys/switchtec-user` and how you downloaded the project to your local machine.

**Comment by thepacketgeek** [comment]
If this is still an issue for you, please re-open with the requested details. Thank you!
